name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
           
            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/shoplifting_model
            if [ ! -d ~/shoplifting_model ]; then
              git clone https://github.com/uctconsulting12/shoplifting_model.git ~/shoplifting_model
            else
              cd ~/shoplifting_model
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/shoplifting_model
            sudo docker build -t shoplifting_image .
            echo "--- remove none images ------"
            sudo docker image prune -f

            echo "---- Stopping old container ----"
            sudo docker stop shoplifting_container || true
            sudo docker rm shoplifting_container || true

            echo "---- Running new container with AWS creds ----"
            sudo docker run -d \
            --name shoplifting_container \
            -p 8003:8003 \
            --gpus all \
            -v /home/ubuntu/.aws:/root/.aws \
            shoplifting_image

            echo "Deployment completed. "